/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidadorRouteImport } from './routes/validador'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as LotesRouteImport } from './routes/lotes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsgRouteImport } from './routes/esg'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConformidadeRouteImport } from './routes/conformidade'
import { Route as CompensarRouteImport } from './routes/compensar'
import { Route as CarteiraRouteImport } from './routes/carteira'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'

const ValidadorRoute = ValidadorRouteImport.update({
  id: '/validador',
  path: '/validador',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const LotesRoute = LotesRouteImport.update({
  id: '/lotes',
  path: '/lotes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsgRoute = EsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConformidadeRoute = ConformidadeRouteImport.update({
  id: '/conformidade',
  path: '/conformidade',
  getParentRoute: () => rootRouteImport,
} as any)
const CompensarRoute = CompensarRouteImport.update({
  id: '/compensar',
  path: '/compensar',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraRoute = CarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carteira': typeof CarteiraRoute
  '/compensar': typeof CompensarRoute
  '/conformidade': typeof ConformidadeRoute
  '/dashboard': typeof DashboardRoute
  '/esg': typeof EsgRoute
  '/login': typeof LoginRoute
  '/lotes': typeof LotesRoute
  '/registro': typeof RegistroRoute
  '/validador': typeof ValidadorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carteira': typeof CarteiraRoute
  '/compensar': typeof CompensarRoute
  '/conformidade': typeof ConformidadeRoute
  '/dashboard': typeof DashboardRoute
  '/esg': typeof EsgRoute
  '/login': typeof LoginRoute
  '/lotes': typeof LotesRoute
  '/registro': typeof RegistroRoute
  '/validador': typeof ValidadorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carteira': typeof CarteiraRoute
  '/compensar': typeof CompensarRoute
  '/conformidade': typeof ConformidadeRoute
  '/dashboard': typeof DashboardRoute
  '/esg': typeof EsgRoute
  '/login': typeof LoginRoute
  '/lotes': typeof LotesRoute
  '/registro': typeof RegistroRoute
  '/validador': typeof ValidadorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/carteira'
    | '/compensar'
    | '/conformidade'
    | '/dashboard'
    | '/esg'
    | '/login'
    | '/lotes'
    | '/registro'
    | '/validador'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/carteira'
    | '/compensar'
    | '/conformidade'
    | '/dashboard'
    | '/esg'
    | '/login'
    | '/lotes'
    | '/registro'
    | '/validador'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/carteira'
    | '/compensar'
    | '/conformidade'
    | '/dashboard'
    | '/esg'
    | '/login'
    | '/lotes'
    | '/registro'
    | '/validador'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CarteiraRoute: typeof CarteiraRoute
  CompensarRoute: typeof CompensarRoute
  ConformidadeRoute: typeof ConformidadeRoute
  DashboardRoute: typeof DashboardRoute
  EsgRoute: typeof EsgRoute
  LoginRoute: typeof LoginRoute
  LotesRoute: typeof LotesRoute
  RegistroRoute: typeof RegistroRoute
  ValidadorRoute: typeof ValidadorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validador': {
      id: '/validador'
      path: '/validador'
      fullPath: '/validador'
      preLoaderRoute: typeof ValidadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lotes': {
      id: '/lotes'
      path: '/lotes'
      fullPath: '/lotes'
      preLoaderRoute: typeof LotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esg': {
      id: '/esg'
      path: '/esg'
      fullPath: '/esg'
      preLoaderRoute: typeof EsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conformidade': {
      id: '/conformidade'
      path: '/conformidade'
      fullPath: '/conformidade'
      preLoaderRoute: typeof ConformidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compensar': {
      id: '/compensar'
      path: '/compensar'
      fullPath: '/compensar'
      preLoaderRoute: typeof CompensarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira': {
      id: '/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof CarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CarteiraRoute: CarteiraRoute,
  CompensarRoute: CompensarRoute,
  ConformidadeRoute: ConformidadeRoute,
  DashboardRoute: DashboardRoute,
  EsgRoute: EsgRoute,
  LoginRoute: LoginRoute,
  LotesRoute: LotesRoute,
  RegistroRoute: RegistroRoute,
  ValidadorRoute: ValidadorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
