/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConformidadeRouteImport } from './routes/conformidade'
import { Route as CadastroRouteImport } from './routes/cadastro'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConformidadeRoute = ConformidadeRouteImport.update({
  id: '/conformidade',
  path: '/conformidade',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/cadastro': typeof CadastroRoute
  '/conformidade': typeof ConformidadeRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
}
export interface FileRoutesByTo {
  '/cadastro': typeof CadastroRoute
  '/conformidade': typeof ConformidadeRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/cadastro': typeof CadastroRoute
  '/conformidade': typeof ConformidadeRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/cadastro'
    | '/conformidade'
    | '/dashboard'
    | '/login'
    | '/registro'
  fileRoutesByTo: FileRoutesByTo
  to: '/cadastro' | '/conformidade' | '/dashboard' | '/login' | '/registro'
  id:
    | '__root__'
    | '/cadastro'
    | '/conformidade'
    | '/dashboard'
    | '/login'
    | '/registro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CadastroRoute: typeof CadastroRoute
  ConformidadeRoute: typeof ConformidadeRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conformidade': {
      id: '/conformidade'
      path: '/conformidade'
      fullPath: '/conformidade'
      preLoaderRoute: typeof ConformidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CadastroRoute: CadastroRoute,
  ConformidadeRoute: ConformidadeRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
