/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRegistroRouteImport } from './routes/_authenticated/registro'
import { Route as AuthenticatedEsgRouteImport } from './routes/_authenticated/esg'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConformidadeRouteImport } from './routes/_authenticated/conformidade'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRegistroRoute = AuthenticatedRegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEsgRoute = AuthenticatedEsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConformidadeRoute =
  AuthenticatedConformidadeRouteImport.update({
    id: '/conformidade',
    path: '/conformidade',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/conformidade': typeof AuthenticatedConformidadeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/esg': typeof AuthenticatedEsgRoute
  '/registro': typeof AuthenticatedRegistroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/conformidade': typeof AuthenticatedConformidadeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/esg': typeof AuthenticatedEsgRoute
  '/registro': typeof AuthenticatedRegistroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/_authenticated/conformidade': typeof AuthenticatedConformidadeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/esg': typeof AuthenticatedEsgRoute
  '/_authenticated/registro': typeof AuthenticatedRegistroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/conformidade'
    | '/dashboard'
    | '/esg'
    | '/registro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/conformidade'
    | '/dashboard'
    | '/esg'
    | '/registro'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/login'
    | '/_authenticated/conformidade'
    | '/_authenticated/dashboard'
    | '/_authenticated/esg'
    | '/_authenticated/registro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/registro': {
      id: '/_authenticated/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof AuthenticatedRegistroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/esg': {
      id: '/_authenticated/esg'
      path: '/esg'
      fullPath: '/esg'
      preLoaderRoute: typeof AuthenticatedEsgRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conformidade': {
      id: '/_authenticated/conformidade'
      path: '/conformidade'
      fullPath: '/conformidade'
      preLoaderRoute: typeof AuthenticatedConformidadeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConformidadeRoute: typeof AuthenticatedConformidadeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEsgRoute: typeof AuthenticatedEsgRoute
  AuthenticatedRegistroRoute: typeof AuthenticatedRegistroRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConformidadeRoute: AuthenticatedConformidadeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEsgRoute: AuthenticatedEsgRoute,
  AuthenticatedRegistroRoute: AuthenticatedRegistroRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
